name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Log in to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    - name: Read version from package.json
      id: version
      run: |
        VERSION=$(jq -r '.version' apps/core/package.json)
        echo "::set-output name=version::$VERSION"
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Build and push the Docker image
      run: |
        VERSION=${{ steps.version.outputs.version }}
        IMAGE_TAG_VERSION=kohlarnhin/mx-core:${VERSION}
        IMAGE_TAG_LATEST=kohlarnhin/mx-core:latest
#        docker buildx build --platform linux/amd64,linux/arm64 --file Dockerfile --tag $IMAGE_TAG_VERSION --tag $IMAGE_TAG_LATEST --push .
        docker buildx build --platform linux/arm64 --file Dockerfile --tag $IMAGE_TAG_VERSION --tag $IMAGE_TAG_LATEST --push .

  
